services:
  mariadb:
    container_name: mariadb 
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose: 
      - "3306/tcp"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on: 
      - wordpress
    restart: unless-stopped
    build:
      context: requirements/nginx
    env_file:
      - .env
    # Mapper le port 443 du conteneur sur le port 443 de la machine locale
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on: 
      - mariadb
    restart: unless-stopped
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    expose: 
      - "9000"

volumes:
  wordpress:
    # Utiliser le driver local pour le volume
    driver: local
    driver_opts:
      # Indique à Docker de ne pas créer un volume virtuel.
      type: 'none'
      # Demande à Docker de travailler directement dans le dossier de l'hôte spécifié.
      o: 'bind'
      device: "/home/lcadinot/data/wordpress"
  mariadb:
    # Utiliser le driver local pour le volume
    driver: local
    driver_opts:
      # Indique à Docker de ne pas créer un volume virtuel.
      type: 'none'
      # Demande à Docker de travailler directement dans le dossier de l'hôte spécifié.
      o: 'bind'
      device: "/home/lcadinot/data/mariadb"

networks:
  inception:
    name: inception
    # Utiliser le driver bridge pour permettre la communication entre les conteneurs
    driver: bridge