FROM mariadb:latest

# Configuration de la base de données
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

VOLUME /var/lib/mysql

CMD ["mysqld"]
